apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: svc1
            port:
              number: 80
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: svc2
            port:
              number: 80
                 
